version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_to_droplet:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Run build
          command: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy-chartwizard.sh"

workflows:
  version: 2
  build-project:
    jobs:
      - build_to_droplet:
          filters:
            branches:
              only:
                - main