version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_to_droplet:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run build
          command: ssh -oStrictHostKeyChecking=no -v $USER@$IP "/opt/chartwizard/deploy.sh"
      - persist_to_workspace:
          root: /opt/chartwizard/
          paths:
            - .

workflows:
  version: 2
  build-project:
    jobs:
      - build_to_droplet:
          filters:
            branches:
              only:
                - main